config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'takes#index'

  resources :takes, only:[:new,:create,:index,:edit,:update,:destroy] do
   resources :orders, only:[:new, :create, :update]
  end
  
  get 'notification' => 'takes#notification'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :take
  
  validates :user_name,presence: true
  validates :take_out,presence: true
end

app/models/take.rb
class Take < ApplicationRecord
  has_many :orders

  validates :name,presence: true
  validates :remaining,presence: true
  validates :lowest,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    notification_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @take = Take.find(params[:take_id])
    @orders = Order.where(take_id: params[:take_id])
    @order = Order.new(take_id: @take.id)
  end

  def create
    @order = Order.new(order_params)
    @order.take_id = params[:take_id]
    @order.save
    
    @take = Take.find(params[:take_id])
    @take.remaining = @take.remaining-@order.take_out
    @take.save

    redirect_to takes_path
  end

  def update
  end

  private
  def order_params
    params.require(:order).permit(:user_name,:take_out)
  end
end

app/controllers/takes_controller.rb
class TakesController < ApplicationController

  def new
    @take = Take.new
  end

  def create
    @take = Take.new(take_params)
    @take.save
    redirect_to root_path
  end

  def index
    @takes = Take.all
    @orders = Order.all
  end

  def edit
    @take = Take.find(params[:id])
  end

  def update
    @take = Take.find(params[:id])
    @take.update(take_params)
    redirect_to takes_path
  end

  def destroy
    @take = Take.find(params[:id])
    @take.destroy
    redirect_to takes_path
  end

  def notification
    @notifications = Take.all
  end

  private
  def take_params
    params.require(:take).permit(:name,:remaining,:lowest)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/takes_helper.rb
module TakesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>McF</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="text-right p-5">
    <% if admin_signed_in? %>
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-danger" %>
        <%= link_to "在庫一覧", takes_path, class: "btn btn-success" %>
        <%= link_to "発注", notification_path, class: "btn btn-success" %>
    <% else %>
        <%= link_to "ログイン", new_admin_session_path, class: "btn btn-info" %>
    <% end %>
   </div>

   <div class="back"><%= link_to "", 'javascript:history.back()', class: "fas fa-undo fa-3x"%></div>
    <%= yield %>
  </body>
</html>

app/views/orders/new.html.erb
<div class="container">
 <div class="row">
  <div class="col">
   <h1>取出</h1>

   <%= form_with model: @order, url: take_orders_path(@take),local:true do |f| %>
    <h3>名前</h3>
    <%= f.text_field :user_name %>
    <h3>数量</h3>
    <%= f.text_field :take_out %>
    <%= f.submit "確定" %>
   <% end %>
  </div>
 </div>

 <div class="row">
  <div class="col mt-5">
   <% @orders.each do |order| %>
   <div class="toridasi">
    <div><%= order.created_at.strftime("%Y/%m/%d")%></div>
    <div class="text-right"><%= order.user_name %></div>
    <div class="text-right border-bottom"><%= order.take_out %></div>
   </div>
   <% end %>
  </div>
 </div>
</div>

app/views/takes/edit.html.erb
<div class="container">
 <div class="row">
  <h1>編集</h1>
  <h6 class="text-danger mt-5">※在庫を追加する時に使用してください。取出に使用しないこと。</h5>
 </div>
   <div class="row">
    <div class="col">
     <%= form_with model:@take, local:true do |f| %>
     <div>
       <%= f.label "商品名　" %>
       <%= f.text_field :name %>
     </div>
     <div>
       <%= f.label "在庫　　"%>
       <%= f.text_field :remaining %>
     </div>
     <div>
       <%= f.label "最低個数" %>
       <%= f.text_field :lowest %>
     </div>
     <div class="touroku">
       <%= f.submit '変更' ,class:"btn btn-info"%>
     </div>
     <% end %>
    </div>
   </div>


<button type="button" class="btn btn-danger rounded-pill btn-lg touroku mt-2" data-toggle="modal" data-target="#exampleModal">
     削除する
    </button>
    <div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
     <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
       <div class="modal-body">
        本当に削除しますか？
       </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <button type="button" class="btn btn-danger">
           <%= link_to "削除", take_path(@take),method: :delete, class: "text-light"%>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/takes/index.html.erb
<div class="container">
 <div class="row">
  <div class="col", style="margin-bottom: 150px; ">
    <h1 class="mt-5">在庫表</h1>
    <div class="text-right">
    <% if current_admin.present? %>
     <%= link_to "", new_take_path,class: "fas fa-plus fa-2x" %>
    <% end %>
    </div>
    <table class="table table-borderd table-hover">
     <thead class="thead-light">
         <tr>
            <th>商品名</th>
            <th>在庫</th>
            <th></th>
         </tr>
     </thead>
     <tbody class="border">
        <% @takes.each do |take| %>
        <tr>
         <td><%= link_to take.name, new_take_order_path(take) %></td>
         <td><%= take.remaining%></td>
         <td><%= link_to "編集", edit_take_path(take) %></td>
        </tr>
        <% end %>
     </tbody>
    </table>
  </div>
 </div>
</div>

app/views/takes/new.html.erb
<div class="container">
 <div class="row">
  <div class="collg-2">
   <h1>新規登録</h1>
  </div>
 </div>
   <%= form_with model:@take, local:true do |f| %>
    <div class="mt-2">
     <%= f.label "商品名　"%>
     <%= f.text_field :name %>
    </div>
    <div class="mt-2">
     <%= f.label "在庫　　"%>
     <%= f.text_field :remaining %>
    </div>
    <div class="mt-2">
     <%= f.label "最低個数" %>
     <%= f.text_field :lowest %>
    </div>
    <div class="mt-5 touroku">
      <%= f.submit '登録', class:"btn btn-info" %>
    </div>
   <% end %>
</div>

app/views/takes/notification.html.erb
<div class="container">
 <div class="row">
  <div class="col">
   <h1>発注</h1>
  </div>
 </div>

 <div class="row">
 <div class="col">
  <% @notifications.each do |take| %>
   <% if take.remaining <= take.lowest %>
   <div class="mt-2">
    <%= take.name + "が残り" + take.remaining.to_s + "です。" %>
    <%= link_to "編集", edit_take_path(take) %>
   </div>
   <% end %>
  <% end %>
 </div>
 </div>
</div>